production:
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  adapter: postgresql
  encoding: unicode
  database: dummy_app_development
  pool: 20
  username: dev-user
  password: 123456
  # port: 5432

development:
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  adapter: postgresql
  encoding: unicode
  database: dummy_app_development
  pool: 20
  username: dev-user
  password: 123456
  # port: 5432

test:
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DATABASE"] || 'dummy_app_test' %>
  pool: 5
  username: dev-user
  password: 123456
  # host: localhost
  # port: 5432
